### ISSUE TITLE
Editor is not working

### ISSUE THREAD

**Issue by Shaihuludus** [Netcentric/access-control-validator#12]
I have problems with editor functionality
1. I can only select path not a file
2. When I select path the next button is not working

**Comment by jochenkoschorke** [comment]
Hi,
The idea is, that you select a folder, containing one ore more testfiles in YAML format.
I checked that again with current release and it was working.

Could you please check again, and if the problem persists, also add more details (AEM version, folder structure, testfile, ...)?

**Comment by Shaihuludus** [comment]
Hi, 

Unfortunately problem is still valid

Content structure: 
/apps/application/acl/tests

test file - tests are working:
- tests:

    - authors:
        - pages:
            
            - path: /content/dam/sites
              actions: read
              permission: allow

            - path: /content/dam/sites
              actions: modify
              permission: deny

AEM version is 6.5.5.0

**Comment by Shaihuludus** [comment]
I also looked into code and I didn't see anything connected to editor except pages.

**Comment by jochenkoschorke** [comment]
I created your folder structure on my local (AEM 6.5.5.0)

I also created a testfile called: "testfile.yaml" with the content you posted (had to change "authors" to "content-authors" as that group did not exist on my local)

I was able to select the "tests" folder in UI, next-button was working, and I was also able to execute the test successfully,

**Comment by Shaihuludus** [comment]
Ok, I am talking about this functionality

/apps/netcentric/acvalidator/tools/editor.html

I suspect it is not ready but when it is visible in AEM it is really confusing

**Comment by jochenkoschorke** [comment]
Sorry, I confused that with the test execution, although you mentioned the editor in your first post. Sorry for that!
Yes, the editor functionality was planned but is not implemented - and you're right, it should actually not appear in the UI atm.

Will remove that option with the next release. Sorry for the confusion.

**Comment by Shaihuludus** [comment]
No problem. Thanks for clarification. Now I know how to present tests to my team.
