### ISSUE TITLE
Where I can find health checks results

### ISSUE THREAD

**Issue by Shaihuludus** [Netcentric/access-control-validator#14]
Hi, 
I configured running tests using health checks but I can't find results. Is there any path where they are stored

**Comment by jochenkoschorke** [comment]
Hi,
Not exactly sure what you configured and how. Normally you can check health reports in the Operations Dashboard (see: https://experienceleague.adobe.com/docs/experience-manager-65/administering/operations/operations-dashboard.html?lang=en#introduction). Is that were you looked at?

**Comment by jochenkoschorke** [comment]
Hi @Shaihuludus ,

Is this issue still relevant?

**Comment by Shaihuludus** [comment]
Sorry, no I found what I needed
